#设置端口
server:
  servlet:
    context-path: /
  error:
    path: error/error_404
  #上线需要改为线上环境的证书和密码
  port: 8000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/javascript,application/javascript,text/css
    min-response-size: 10
    excluded-user-agents: gozilla,traviata
thread:
  core-pool-size: 20
  max-pool-size: 200
  allow-coreThread-timeOut: true
  queue-capacity: 200
  keep-alive-seconds: 500
#博客版本信息
blog:
  version: 1.2
  author: dddpeter
  #博客的开始运行日期
  run:
    date: 2021-01-01

spring:
  profiles:
    active: ${ENV:dev}
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  #关闭自动context /
  application:
    name: blog
  #设置模板引擎
  thymeleaf:
    mode: HTML
    #热部署文件，页面不产生缓存，及时更新
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    enabled: true
  output:
    ansi:
      #设置彩色输出
      enabled: always
  #guava 设置
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath*:/META-INF/resources/webjars/,classpath*:/META-INF/resources/
guava:
  time: 1
  max-size: 100
    #配置日志级别
# Mybatis plus设置
mybatis-plus:
  type-aliases-package: club.javafan.blog.domain
  mapper-locations: classpath*:mapper/*.xml
